baseURL = 'https://deroise2306.github.io' # Thay bằng link Vercel sau này
languageCode = 'vi-vn'
title = "deroise2306's Home"
theme = 'Reimu'

[author]
  name = 'deroise2306'

[params]
  description = 'hello'